In [1]:
import spacy
import pandas as pd

try:
      nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading language model...")
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

print("✅ Libraries imported and Model loaded!")

✅ Libraries imported and Model loaded!

In [8]:
with open("Edwards_Full_Text.txt", "r", encoding="utf-8") as infile:
  E_full_text = infile.read()

print(f"Download complete. Total characters: {len(E_full_text)}")
print("-" * 50)
print(E_full_text[0:500])

Download complete. Total characters: 706715
--------------------------------------------------
First'  arrival  of  the  English  at  this  islaad.— -Origin,  pro¬
gress,  and  termination  of  the  proprietary  government.
Revenue  granted  to  the  crown  of  four  and  a  half  per
centum  on  all  produce  exported — how  obtained.— Origin
of  the  act  of  navigation. — Situation  and  extent  of  the
island. — Soil  and  produce. — Population. — Decline,  and
causes  thereof. — Exports  and  imports.

THE  island  of  Barbadoes*  of  which  I  now  pro¬
pose  to  treat,  was

In [9]:
print("Processing text pipeline... (this may take a moment)")
E_doc_full_text = nlp(E_full_text)

print("Processing complete!")
print(f"Processed {len(E_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 706715 characters from the full text.

In [11]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

E_matching_female_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in female_terms:
        E_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        E_matching_female_tokens.append(token.lemma_.lower())

In [12]:
E_df_female_mentions = pd.Series(E_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(E_df_female_mentions.head(20))

Top mentions of female-related terms:

        index  Counts
0       women      27
1       woman      17
2      mother      15
3     females      15
4        wife      13
5       wives      11
6      ladies       5
7      female       5
8        girl       4
9      sister       3
10    mothers       3
11  daughters       2
12   daughter       2
13      girls       2
14       lady       1
15    sisters       1

In [13]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

E_matching_male_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in male_terms:
        E_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        E_matching_male_tokens.append(token.lemma_.lower())

E_df_male_mentions = pd.Series(E_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(E_df_male_mentions.head(20))

Top mentions of male-related terms:

       index  Counts
0        man     104
1        men      95
2     father      18
3        son      16
4    brother      16
5      males      12
6        boy       8
7       sons       8
8       boys       6
9    husband       4
10   fathers       4
11  husbands       2
12  brothers       2
13      male       2