Final Project:
Gendered Language Respository in Colonial Caribbean Historical texts from early 19th century.

In [31]:
import spacy
import pandas as pd

try:
      nlp = spacy.load("en_core_web_sm")
except OSError:
    print("Downloading language model...")
    from spacy.cli import download
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")

print("✅ Libraries imported and Model loaded!")

✅ Libraries imported and Model loaded!

It is key to ensure that as I work with each text, I assign unique variables for each text file. This way, I can ensure the data will be processed seperately. Code involing Rainford's text will be marked using the letter "R" in the begining of the variable name. "E" will be used for code involving the analysis of Edwards' text. "L" will be placed in front of variables concerning itself with Long's text.

Rainsford

In [32]:
with open("Rainsford_Full_Text.txt", "r", encoding="utf-8") as infile:
  R_full_text = infile.read()

print(f"Download complete. Total characters: {len(R_full_text)}")
print("-" * 50)
print(R_full_text[0:1000])

Download complete. Total characters: 601736
--------------------------------------------------
INTRODUCTION.


It has frequently been the fate of striking events, and particularly those which
have altered the condition of mankind, to be denied that consideration by
their contemporaries, which they obtain from the veneration of posterity. In
their vortex, attention is distracted by the effects; and distant society recedes
from the contemplation of objects that threaten a violation of their system,
or wound a favourite prejudice. It is thus that history, with all the advantages
of calm discussion, is imperfect; and philosophy enquires in vain for the un-
recorded causes of astonishing transactions.

To remedy the evil in this enlightened æra, the disquisitions of the ob-
server, and the relations of the traveller occur; but these are perused with the
rapidity, with which they are necessarily made, and, although they teach us
what regards our own nature, impress no other sense of the period described,
than as relates to the fleeting objects of immediate import— furnish

In [33]:
print("Processing text pipeline... (this may take a moment)")
R_doc_full_text = nlp(R_full_text)

print("Processing complete!")
print(f"Processed {len(R_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 601736 characters from the full text.

In [34]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

R_matching_female_tokens = []
for token in R_doc_full_text:
    if token.text.lower() in female_terms:
        R_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        R_matching_female_tokens.append(token.lemma_.lower())

R_df_female_mentions = pd.Series(R_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(R_df_female_mentions.head(20))

Top mentions of female-related terms:

        index  Counts
0      mother      50
1        wife      16
2       women      15
3      female      11
4       woman       7
5     females       6
6      sister       6
7        lady       4
8      ladies       4
9       wives       3
10   daughter       3
11    mothers       3
12    sisters       2
13  daughters       1

In [35]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

R_matching_male_tokens = []
for token in R_doc_full_text:
    if token.text.lower() in male_terms:
        R_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        R_matching_male_tokens.append(token.lemma_.lower())

R_df_male_mentions = pd.Series(R_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(R_df_male_mentions.head(20))

Top mentions of male-related terms:

       index  Counts
0        men     101
1        man      65
2    brother      28
3        son      12
4     father      12
5   brothers      11
6       sons       8
7    fathers       3
8    husband       3
9   husbands       2
10      male       2
11       boy       1
12     males       1

Edwards

Number of female and male gender words used in Bryan Edward's "The history, civil and commercial, of the British colonies in the West Indies"

In [36]:
with open("Edwards_Full_Text.txt", "r", encoding="utf-8") as infile:
  E_full_text = infile.read()

print(f"Download complete. Total characters: {len(E_full_text)}")
print("-" * 50)
print(E_full_text[0:500])

Download complete. Total characters: 706715
--------------------------------------------------
First'  arrival  of  the  English  at  this  islaad.— -Origin,  pro¬
gress,  and  termination  of  the  proprietary  government.
Revenue  granted  to  the  crown  of  four  and  a  half  per
centum  on  all  produce  exported — how  obtained.— Origin
of  the  act  of  navigation. — Situation  and  extent  of  the
island. — Soil  and  produce. — Population. — Decline,  and
causes  thereof. — Exports  and  imports.

THE  island  of  Barbadoes*  of  which  I  now  pro¬
pose  to  treat,  was

In [37]:
print("Processing text pipeline... (this may take a moment)")
E_doc_full_text = nlp(E_full_text)

print("Processing complete!")
print(f"Processed {len(E_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 706715 characters from the full text.

In [38]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

E_matching_female_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in female_terms:
        E_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        E_matching_female_tokens.append(token.lemma_.lower())

E_df_female_mentions = pd.Series(E_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(E_df_female_mentions.head(20))

Top mentions of female-related terms:

        index  Counts
0       women      27
1       woman      17
2      mother      15
3     females      15
4        wife      13
5       wives      11
6      ladies       5
7      female       5
8        girl       4
9      sister       3
10    mothers       3
11  daughters       2
12   daughter       2
13      girls       2
14       lady       1
15    sisters       1

In [39]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

E_matching_male_tokens = []
for token in E_doc_full_text:
    if token.text.lower() in male_terms:
        E_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        E_matching_male_tokens.append(token.lemma_.lower())

E_df_male_mentions = pd.Series(E_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(E_df_male_mentions.head(20))

Top mentions of male-related terms:

       index  Counts
0        man     104
1        men      95
2     father      18
3        son      16
4    brother      16
5      males      12
6        boy       8
7       sons       8
8       boys       6
9    husband       4
10   fathers       4
11  husbands       2
12  brothers       2
13      male       2

Edward Long "History of the island of St. Domingo, from its first discovery by Columbus to the present period." Printed, 1818

In [40]:
with open("Long_Full_Text.txt", "r", encoding="utf-8") as infile:
  L_full_text = infile.read()

print(f"Download complete. Total characters: {len(L_full_text)}")
print("-" * 50)
print(L_full_text[0:200])

Download complete. Total characters: 650071
--------------------------------------------------
OF

CHAPTER  I.

FROM  THE  PERIOD  OF  THE  DISCOVERY  OF  THE  ISLAND,  TO
THE  YEAR  1600.

Situation. — General  description. — Discovery  hy  Columhus. — State  of
theinhahitants. — Anecdote

In [41]:
print("Processing text pipeline... (this may take a moment)")
L_doc_full_text = nlp(L_full_text)

print("Processing complete!")
print(f"Processed {len(L_full_text)} characters from the full text.")

Processing text pipeline... (this may take a moment)
Processing complete!
Processed 650071 characters from the full text.

In [42]:
female_terms = [
    'woman', 'women', 'female', 'females', 'girl', 'girls',
    'lady', 'ladies', 'mother', 'mothers', 'daughter', 'daughters',
    'wife', 'wives', 'sister', 'sisters'
]

L_matching_female_tokens = []
for token in L_doc_full_text:
    if token.text.lower() in female_terms:
        L_matching_female_tokens.append(token.text.lower())
    elif token.lemma_.lower() in female_terms:
        L_matching_female_tokens.append(token.lemma_.lower())

L_df_female_mentions = pd.Series(L_matching_female_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of female-related terms:")
display(L_df_female_mentions.head(20))

Top mentions of female-related terms:

        index  Counts
0      mother      21
1       women      16
2        wife      16
3       wives       7
4       woman       4
5   daughters       3
6     females       3
7      female       2
8    daughter       2
9     mothers       2
10      girls       1
11     ladies       1
12    sisters       1

In [43]:
male_terms = [
    'man', 'men', 'male', 'males', 'boy', 'boys',
    'father', 'fathers', 'son', 'sons',
    'husband', 'husbands', 'brother', 'brothers'
]

L_matching_male_tokens = []
for token in L_doc_full_text:
    if token.text.lower() in male_terms:
        L_matching_male_tokens.append(token.text.lower())
    elif token.lemma_.lower() in male_terms:
        L_matching_male_tokens.append(token.lemma_.lower())

L_df_male_mentions = pd.Series(L_matching_male_tokens).value_counts().reset_index(name='Counts')

print("Top mentions of male-related terms:")
display(L_df_male_mentions.head(20))

Top mentions of male-related terms:

       index  Counts
0        men     108
1        man      57
2    brother      35
3        son      16
4       sons      15
5     father      13
6    husband       9
7       male       7
8    fathers       7
9   brothers       6
10     males       2
11       boy       1